services:
  - type: web
    name: voice-scribe
    env: node
    plan: starter
    repo: https://github.com/OpenPecha/Voice-Scribe.git
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: voice-scribe-pg
          property: connectionString

databases:
  - name: voice-scribe-pg
    type: postgres
    plan: free
    instanceType: basic
    storage: 10
